server:
  port: 8081

# Eureka
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true

# Spring
spring:
  application:
    name: api-gateway
    gateway:
      routes:
        - id: promotion
          uri: http://promotion:9500
          predicates:
            - Path=/promotions/v1/promotions/all/banners
          filters:
            - StripPrefix=1